const restList = [
  {
    id: '579525',
    name: 'Sri Sakthi Mess',
    cloudinaryImageId: 'ewshoqa9wdjhigg6pho5',
    locality: 'Vaikkal Road',
    areaName: 'Gobichettipalayam',
    costForTwo: '₹200 for two',
    cuisines: ['South Indian'],
    avgRating: 3.3,
  },
  {
    id: '547156',
    name: 'Sachitha Nanthini Mess',
    cloudinaryImageId: 'qidspzontxonxliy3ub4',
    locality: 'Yakoop Street',
    areaName: 'Gobichettipalayam',
    costForTwo: '₹200 for two',
    cuisines: ['South Indian', 'Chinese'],
    avgRating: 4.5,
  },
  {
    id: '916626',
    name: 'Garden Restaurant',
    cloudinaryImageId:
      'RX_THUMBNAIL/IMAGES/VENDOR/2024/6/27/1192d919-7f8c-4cea-962c-180a8d599ff8_916626.jpg',
    locality: 'Modachur Rd',
    areaName: 'Gobichettipalayam',
    costForTwo: '₹200 for two',
    cuisines: ['South Indian', 'Indian'],
    avgRating: 4.6,
  },
  {
    id: '498262',
    name: 'Yazh Restaurant',
    cloudinaryImageId: 'jg8ptjemzkktawhi8c62',
    areaName: 'Gobichettipalayam',
    costForTwo: '₹300 for two',
    cuisines: ['Chinese', 'South Indian'],
    avgRating: 3.8,
  },
  {
    id: '555188',
    name: 'Pandian Mess',
    cloudinaryImageId: 'wnn7npcw3rxoaajl4nbz',
    locality: 'Modachur Road',
    areaName: 'Gobichettipalayam',
    costForTwo: '₹200 for two',
    cuisines: ['South Indian'],
    avgRating: 4.3,
  },
  {
    id: '902431',
    name: 'Jayasai Fruits',
    cloudinaryImageId:
      'RX_THUMBNAIL/IMAGES/VENDOR/2024/5/31/ba495002-7e20-40d0-b0cc-2f9d200d088c_902431.jpg',
    locality: 'Ther Veedhi',
    areaName: 'Gobichettipalayam',
    costForTwo: '₹200 for two',
    cuisines: ['Juices', 'Snacks', 'Fast Food'],
    avgRating: 5,
  },
  {
    id: '726902',
    name: 'Town Biriyani Hotel',
    cloudinaryImageId: 'b14cd9fc40129fcfb97aa7e621719d07',
    locality: 'Main Road',
    areaName: 'Gobichettipalayam',
    costForTwo: '₹250 for two',
    cuisines: ['Indian', 'Chinese', 'Snacks'],
    avgRating: 4.1,
  },
  {
    id: '497829',
    name: 'Chill Bite',
    cloudinaryImageId: 'ga8xwhtmilmpfiri7laz',
    locality: 'New Hospital Road',
    areaName: 'Gobichettipalayam',
    costForTwo: '₹500 for two',
    cuisines: ['Italian', 'Pizzas'],
    avgRating: 4,
  },
];

export { restList };
